version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-microservices
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-microservices
    ports:
      - "5672:5672"   # Port AMQP
      - "15672:15672" # Port Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 10s
      retries: 10

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_NAME: users_db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DIALECT: mysql
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DB_NAME: accounts_db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DIALECT: mysql
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

volumes:
  mysql-data:
